# Generated by Django 5.2.8 on 2025-11-23 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_farm_user_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invitation_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_password_temporary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_add_logs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.farm'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('manager', 'Manager'), ('superuser', 'Superuser')], default='staff', max_length=50),
        ),
    ]
