# Generated by Django 5.2.8 on 2025-11-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_invitation_code_user_is_password_temporary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_joined',
            field=models.BooleanField(default=False),
        ),
    ]
