# Generated by Django 5.2.8 on 2025-11-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_password_reset_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
