# Generated by Django 6.0.1 on 2026-01-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_password_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('manager', 'Manager'), ('financial_manager', 'Financial Manager'), ('superuser', 'Superuser')], default='staff', max_length=50),
        ),
    ]
