DEFAULT_QUESTIONS = [
    {"text": "Birds received (new placement)", "type": "number"},
    {"text": "Mortality (by cause)", "type": "text"},
    {"text": "Culls", "type": "number"},
    {"text": "Transfers between houses", "type": "text"},
    {"text": "Closing stock (auto-calculated)", "type": "number"},
    {"text": "Stock variance alerts", "type": "text"},
    {"text": "Feed batch number", "type": "text"},
    {"text": "Feed issued (kg)", "type": "number"},
    {"text": "Feed consumed (kg)", "type": "number"},
    {"text": "Feed wastage", "type": "text"},
    {"text": "Feed balance (auto)", "type": "number"},
    {"text": "FCR (Feed Conversion Ratio – auto)", "type": "number"},
    {"text": "Feed days remaining (forecast)", "type": "number"},
    {"text": "Water consumption (litres)", "type": "number"},
    {"text": "Water source", "type": "text"},
    {"text": "Drinkers condition", "type": "text"},
    {"text": "Abnormal water intake alerts", "type": "text"},
    {"text": "Water-to-feed ratio (auto)", "type": "number"},
    {"text": "Sample bird weight", "type": "number"},
    {"text": "Average live weight", "type": "number"},
    {"text": "Uniformity %", "type": "number"},
    {"text": "Daily weight gain", "type": "number"},
    {"text": "Expected vs actual growth", "type": "text"},
    {"text": "House temperature (min/max)", "type": "text"},
    {"text": "Humidity", "type": "number"},
    {"text": "Ventilation status", "type": "text"},
    {"text": "Ammonia smell level", "type": "text"},
    {"text": "Lighting hours", "type": "number"},
    {"text": "Litter condition", "type": "text"},
    {"text": "Heat stress indicators", "type": "text"},
    {"text": "Environmental threshold alerts", "type": "text"},
    {"text": "Feeders condition", "type": "text"},
    {"text": "Fans/heaters status", "type": "text"},
    {"text": "Generator runtime", "type": "text"},
    {"text": "Equipment faults reported", "type": "text"},
    {"text": "Maintenance actions taken", "type": "text"},
]
