# Generated by Django 6.0.1 on 2026-01-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportconfig',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
