# Generated by Django 5.2.8 on 2025-11-19 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('initial_quantity', models.PositiveIntegerField()),
                ('current_quantity', models.PositiveIntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feed_type', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_logs', to='flocks.flock')),
            ],
        ),
        migrations.CreateModel(
            name='EggCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_collected', models.PositiveIntegerField()),
                ('damaged', models.PositiveIntegerField(default=0)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_collections', to='flocks.flock')),
            ],
        ),
        migrations.CreateModel(
            name='HealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('log_type', models.CharField(choices=[('vaccination', 'Vaccination'), ('medication', 'Medication'), ('mortality', 'Mortality'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('affected_birds', models.PositiveIntegerField(default=0)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='flocks.flock')),
            ],
        ),
    ]
