# Generated by Django 5.2.8 on 2025-12-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_transaction_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('feed', 'Feed'), ('medication', 'Medication'), ('equipment', 'Equipment'), ('labor', 'Labor'), ('utilities', 'Utilities'), ('egg_sales', 'Egg Sales'), ('bird_sales', 'Bird Sales'), ('manure_sales', 'Manure Sales'), ('other', 'Other')], max_length=50),
        ),
    ]
